######################################################################
# Automatically generated by qmake (2.01a) Wed May 1 15:41:52 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /ad/eng/users/j/s/jstern19/Project/ul/new_lcd/. .

# Input
HEADERS += firstwindow.h
FORMS += firstwindow.ui
SOURCES += firstwindow.cpp main.cpp
